export const languages = [
  "English en",
  "Mandarin Chinese zh",
  "Hindi hi",
  "Spanish es",
  "French fr",
  "Arabic ar",
  "Russian ru",
  "Portuguese pt",
  "Urdu ur",
  "Indonesian id",
  "German de",
  "Japanese ja",
  "Marathi mr",
  "Turkish tr",
  "Vietnamese vi",
  "Korean ko",
  "Italian it",
  "Swahili sw",
  "Dutch nl",
  "Polish pl",
  "Telugu te",
  "Thai th",
  "Gujarati gu",
  "Malayalam ml",
  "Punjabi pa",
  "Ukrainian uk",
  "Burmese my",
  "Wu (Shanghainese) wu",
  "Hausa ha",
  "Tamil ta",
  "Bhojpuri bho",
  "French Creole fc",
  "Javanese jv",
  "Bengali bn",
  "Yoruba yo",
  "Minangkabau min",
  "Amharic am",
  "Bengali bn",
  "German de",
  "French fr",
  "Italian it",
  "Japanese ja",
  "Korean ko",
  "Portuguese pt",
  "Russian ru",
  "Spanish es",
  "Swahili sw",
  "Turkish tr",
  "Vietnamese vi",
];
