export const webCategory = [
  "Social Media",
  "News",
  "E-commerce",
  "Blogs",
  "Educational",
  "Entertainment",
  "Technology",
  "Health",
  "Travel",
  "Sports",
  "Finance",
  "Government",
  "Business",
  "Personal",
  "Community",
  "Gaming",
  "Food and Drink",
  "Music",
  "Art and Design",
  "Science",
  "Fashion",
  "Photography",
  "Automotive",
  "Job Portals",
  "Weather",
  "Utilities",
  "Non-profit",
  "Other",
];
